log:
  loglevel: info
dns:
  servers:
  - https+local://1.1.1.1/dns-query
inbounds:
- port: 8080
  protocol: vless
  settings:
    clients:
    - id: "b895cc48-6676-409b-be5f-c52e6b217704"
    decryption: "none"
  streamSettings:
    network: ws
    wsSettings:
      path: vless
  sniffing:
    enabled: true
    destOverride:
    - http
    - tls
outbounds:
- protocol: freedom
  tag: direct
  settings:
    domainStrategy: UseIPv4
